// CBI team member data — drives both the team list and individual profile pages

export type TeamLevel = 'executive' | 'thematic' | 'departmental'

export interface TeamMember {
  slug:        string
  name:        string
  role:        string
  email:       string
  photo:       string
  accent:      string
  level:       TeamLevel
  bio:         string            // long-form bio for profile page
  shortBio?:   string            // truncated bio for the card grid
  quote:       string
  yearsAtCBI:  number
  location:    string
  expertise:   string[]
  languages:   string[]
  education?:  string[]
  achievements?: string[]
  linkedin?:   string
}

export const TEAM: TeamMember[] = [

  /* ─── EXECUTIVE TEAM ─────────────────────────────────────── */
  {
    slug:       'rejoice-mark',
    name:       'Rejoice Mark',
    role:       'Executive Director',
    email:      'rejoice@cbi.ngo',
    photo:      '/images/team/rejoice.jpg',
    accent:     '#0102F1',
    level:      'executive',
    location:   'Abuja, Nigeria',
    yearsAtCBI: 7,
    bio:        "Rejoice founded Care Best Initiative in 2019 with a vision to deliver integrated humanitarian care to Nigeria's most vulnerable communities. She brings over 15 years of NGO leadership experience across the North-East and North-West regions, and has led CBI from a 7-person team to a national organisation serving 1,500,000+ beneficiaries across 10 states. Under her leadership, CBI has built partnerships with UNICEF, WFP, USAID, FCDO, and 35+ international humanitarian organisations. She is a frequent speaker at humanitarian convenings on community-led programming and women's leadership in NGOs.",
    shortBio:   "Founded CBI in 2019. Brings over 15 years of NGO leadership across North-East and North-West Nigeria.",
    quote:      'We started with seven people and a mission. Today we reach 1,500,000.',
    expertise:  ['Humanitarian Strategy', 'Organisational Leadership', 'Partnership Development', 'Programme Design', "Women's Leadership"],
    languages:  ['English', 'Hausa', 'Pidgin English'],
    education:  ['MSc Public Health, University of Ibadan', 'BSc Sociology, University of Maiduguri'],
    achievements: [
      'Founded CBI and scaled to 1,500,000+ beneficiaries',
      'Built partnerships with UNICEF, WFP, USAID, FCDO and 35+ organisations',
      'Expanded from 1 to 10 Nigerian states in 6 years',
      'Recognised as a trusted implementing partner by USAID',
    ],
    linkedin:   '#',
  },
  {
    slug:       'thomas-dayo',
    name:       'Thomas Umazayi Dayo',
    role:       'Program Manager',
    email:      'thomas@cbi.ngo',
    photo:      '/images/team/thomas.jpg',
    accent:     '#0102F1',
    level:      'executive',
    location:   'Abuja, Nigeria',
    yearsAtCBI: 5,
    bio:        "Thomas oversees CBI's program portfolio across all six thematic areas — Health & Primary Care, Nutrition, WASH, Protection & GBV, Food Security & Livelihoods, and Education in Emergency. He ensures quality delivery and alignment with international humanitarian standards (Sphere, CHS), and coordinates daily with UNICEF, WFP, and 35+ partner organisations on programme design, implementation, and reporting. His background in MEAL gives him a sharp focus on evidence-based programming and accountability.",
    shortBio:   "Oversees CBI's full programme portfolio across all six thematic areas. Coordinates with 35+ partner organisations.",
    quote:      'Programs are only as good as the field officers who deliver them.',
    expertise:  ['Programme Management', 'MEAL', 'Sphere Standards', 'Partnership Coordination', 'Field Operations'],
    languages:  ['English', 'Hausa', 'Kanuri'],
    education:  ['MSc Development Studies, University of Jos', 'BSc Public Administration, ABU Zaria'],
    achievements: [
      'Manages 6 programmes across 10 states',
      'Coordinates 35+ partner relationships',
      'Led roll-out of CBI MEAL framework',
    ],
    linkedin:   '#',
  },

  /* ─── THEMATIC LEADERS ────────────────────────────────────── */
  {
    slug:       'dorcas-omajali',
    name:       'Dr. Dorcas Ehi Omajali',
    role:       'Health Coordinator',
    email:      'health@cbi.ngo',
    photo:      '',
    accent:     '#e11d48',
    level:      'thematic',
    location:   'Maiduguri, Borno',
    yearsAtCBI: 1,
    bio:        "Dr. Dorcas Ehi Omajali is a medical doctor serving as Health Coordinator at Care Best Initiative, combining clinical expertise with a passion for health advocacy and community education. With her MBBS degree, Dr. Dorcas is dedicated to improving health outcomes through education and advocacy, with a particular focus on empowering women and girls. As a skilled public speaker and health advocate, she works to bridge the gap between medical knowledge and community understanding. Her leadership was evident as the first female president of the Benue Medical Students Association (BEMSA-BSU), where she revitalised the organisation and established it as an active platform for student engagement. She is also a former volunteer for the Hand of Favor Global Care Support Foundation, where she led outreaches for IDPs, conflict-affected persons, and orphans.",
    shortBio:   "Medical doctor combining clinical expertise with health advocacy and community education, with a focus on women and girls.",
    quote:      'Informed communities are healthier communities.',
    expertise:  ['Clinical Medicine', 'Health Coordination & Program Management', 'Health Education & Community Awareness', 'Public Health Advocacy', "Women and Girls' Health Empowerment", 'Community Engagement & Outreach', 'Humanitarian Health Response'],
    languages:  ['English'],
    education:  ['MBBS, Benue State University, Makurdi'],
    achievements: [
      'First female president of Benue Medical Students Association (BEMSA-BSU)',
      'Led outreaches to IDPs, conflict-affected persons and orphans',
    ],
    linkedin:   'https://www.linkedin.com/in/dorcas-omajali-04911a18a',
  },
  {
    slug:       'william-ede',
    name:       'William Okpunyi Ede',
    role:       'Nutrition Coordinator',
    email:      'nutrition@cbi.ngo',
    photo:      '/images/team/william.jpg',
    accent:     '#0102F1',
    level:      'thematic',
    location:   'Maiduguri, Borno',
    yearsAtCBI: 1,
    bio:        "William Okpunyi Ede is a Registered Nurse, Midwife, and Public Health Nurse with a Bachelor of Nursing Science from Ahmadu Bello University, Zaria. With over five years of clinical and community health experience, he currently leads nutrition coordination and health program support at Care Best Initiative. A 2025 Aspire Fellow and alumnus of Harvard-facilitated leadership masterclasses, William brings a strong commitment to public health advocacy, research, and community development. He has volunteered with the Olusegun Obasanjo Foundation and the No One Behind Foundation, providing care and counselling to underserved populations across Nigeria. Beyond healthcare, William is a creative professional with expertise in graphic design and content creation.",
    shortBio:   "Registered Nurse, Midwife, and Public Health Nurse leading nutrition coordination at CBI. 2025 Aspire Fellow.",
    quote:      'Every child deserves a healthy start.',
    expertise:  ['Project Management', 'Program Implementation', 'Community Health Outreach', 'Public Health Advocacy', 'Supervisory & Team Leadership', 'Monitoring & Evaluation', 'Emergency Health Response'],
    languages:  ['English'],
    education:  ['BNSc Nursing Science, Ahmadu Bello University, Zaria'],
    achievements: [
      '2025 Aspire Fellow',
      'Harvard-facilitated leadership masterclass alumnus',
      'Volunteered with Olusegun Obasanjo Foundation',
    ],
    linkedin:   'https://www.linkedin.com/in/william-ede-0367a3229',
  },
  {
    slug:       'hyelafiya-hassan',
    name:       'Hyelafiya Sani Hassan',
    role:       'WASH Coordinator',
    email:      'wash@cbi.ngo',
    photo:      '',
    accent:     '#0891b2',
    level:      'thematic',
    location:   'Maiduguri, Borno',
    yearsAtCBI: 4,
    bio:        "Hyelafiya Sani Hassan is a seasoned WASH professional and an indigene of Askira/Uba LGA, bringing over a decade of experience in humanitarian and development programming across Northeast and Northwest Nigeria. He is passionate about strengthening communities through effective Water, Sanitation, and Hygiene (WASH) interventions, with a strong focus on coordination, emergency response, public health, and community-driven development. Throughout his career, Hyelafiya has played a key role in the design, implementation, coordination, and monitoring of WASH programs in both emergency and recovery contexts. He has worked collaboratively with government bodies, humanitarian partners, donors, and local communities to deliver impactful and sustainable interventions.",
    shortBio:   "Seasoned WASH professional with over a decade of experience in humanitarian programming across Northeast and Northwest Nigeria.",
    quote:      'Safe water is not a luxury — it is a human right.',
    expertise:  ['WASH Coordination', 'Humanitarian Response', 'Emergency WASH Programming', 'Cholera/AWD Response', 'Water Supply Systems', 'Sanitation and Hygiene Promotion', 'Community Engagement'],
    languages:  ['English', 'Hausa', 'Kanuri'],
    education:  ['Executive MBA, E-Health and Management, Rome Business School Nigeria', 'BSc Ed, Health Education, University of Maiduguri'],
    achievements: [
      'Over a decade of WASH programming in Northeast and Northwest Nigeria',
      'Executive MBA in E-Health and Management',
    ],
    linkedin:   'https://www.linkedin.com/in/hyelafiya-sani-hassan-6a3b52142',
  },
  {
    slug:       'faith-affuafor',
    name:       'Faith Affuafor',
    role:       'Education Coordinator',
    email:      'education@cbi.ngo',
    photo:      '/images/team/faith.jpg',
    accent:     '#0102F1',
    level:      'thematic',
    location:   'Borno State, Nigeria',
    yearsAtCBI: 4,
    bio:        "Faith Affuafor is an experienced education and humanitarian professional with over five years of multi-sectoral experience in program coordination, education in emergencies, community engagement, and inclusive education programming. She currently serves as the Education Coordinator at Care Best Initiative, leading the design, implementation, monitoring, and evaluation of education interventions for vulnerable and crisis-affected communities. She holds a Bachelor's degree in Microbiology from Kano State University of Science and Technology and an MBA from MIVA Open University. She has completed professional certifications in Education in Emergencies, Infection Prevention and Control, Safeguarding, Disability Inclusion, and Complex Humanitarian Emergencies through WHO, UNICEF, and Humanitarian Academy at Harvard.",
    shortBio:   "Education specialist with 5+ years of experience in emergency education programming and inclusive learning across Northeast Nigeria.",
    quote:      'Every child in crisis still has the right to learn.',
    expertise:  ['Humanitarian Programming', 'Education Program Coordination', 'Project Planning and Implementation', 'Community Engagement and Mobilization', 'Teacher Training and Capacity Building', 'Disability Inclusion', 'Proposal Writing and Donor Reporting'],
    languages:  ['English', 'Hausa'],
    education:  ['MBA, MIVA Open University', 'BSc Microbiology, Kano State University of Science and Technology'],
    achievements: [
      'Certified in Education in Emergencies (UNICEF)',
      'Humanitarian Academy at Harvard alumna',
      'Supported re-enrollment of out-of-school children across Northeast Nigeria',
    ],
    linkedin:   'https://www.linkedin.com/in/faith-affuafor-96581928b',
  },
  {
    slug:       'patience-ameh',
    name:       'Patience Enecheojo Ameh',
    role:       'Protection Coordinator',
    email:      'protection@cbi.ngo',
    photo:      '/images/team/patience.jpg',
    accent:     '#0102F1',
    level:      'thematic',
    location:   'Borno, Nigeria',
    yearsAtCBI: 5,
    bio:        "Patience Enecheojo Ameh is a dedicated and compassionate humanitarian and protection professional with extensive experience in Gender-Based Violence (GBV), Child Protection, safeguarding, and community-based interventions across Nigeria. She is passionate about supporting vulnerable populations and has successfully led protection programs, strengthened safeguarding systems, and facilitated impactful capacity-building initiatives in humanitarian settings. She brings strong expertise in protection interventions, PSEAH, community engagement, referral pathway development, and multi-sectoral coordination. Known for her leadership and stakeholder engagement skills, she applies survivor-centred approaches that promote dignity, safety, and resilience among affected communities.",
    shortBio:   "Protection specialist with 5 years of experience in GBV response, child safeguarding, and PSEAH across humanitarian settings.",
    quote:      'Dignity cannot wait. Protection is always urgent.',
    expertise:  ['Protection Programming', 'Gender-Based Violence Response', 'Child Protection', 'Safeguarding & PSEAH', 'Community Engagement', 'Referral Pathway Development', 'Multi-sectoral Coordination'],
    languages:  ['English', 'Hausa'],
    education:  ['BTech Chemistry Education', 'MSc Social Work (in progress)'],
    achievements: [
      'Led protection programs across humanitarian settings in Borno',
      '5 years of GBV and child protection programming',
    ],
    linkedin:   'https://www.linkedin.com/in/patience-ameh-318ab228b/',
  },
  {
    slug:       'elraham-zoaka',
    name:       'El-raham Mbursa Zoaka',
    role:       'FSL Coordinator',
    email:      'fsl@cbi.ngo',
    photo:      '/images/team/elraham.jpg',
    accent:     '#0102F1',
    level:      'thematic',
    location:   'Borno State, Nigeria',
    yearsAtCBI: 4,
    bio:        "El-raham Mbursa Zoaka is a proficient, resourceful, and result-driven Nigerian Animal Scientist and Food Security & Livelihood (FSL) and nutrition professional with a Master's degree in Animal Science (Animal Physiology) from the University of Maiduguri. He currently serves as FSL Coordinator at Care Best Initiative, providing leadership in the design and implementation of food security, livelihood, and nutrition interventions aimed at improving household resilience and well-being. He has built a progressive career spanning academia, agricultural practice, and humanitarian development, with practical expertise in crop and livestock production, farm management, community engagement, capacity building, project implementation, and research.",
    shortBio:   "Food Security & Livelihoods specialist with a Master's in Animal Science, leading FSL programming at CBI.",
    quote:      'Lasting food security begins with empowering communities to feed themselves.',
    expertise:  ['Food Security, Livelihood and Nutrition Programming', 'Humanitarian Coordination', 'Emergency Response', 'Project Management', 'Agriculture, Livestock and Poultry Production', 'Research and Data Analysis', 'Capacity Building'],
    languages:  ['English', 'Hausa', 'Kanuri'],
    education:  ["Master's in Animal Science (Animal Physiology), University of Maiduguri", 'BSc Animal Science, University of Maiduguri'],
    achievements: [
      'Member, Nigerian Institute of Animal Science',
      'Certified, Project Management for Development Professionals (Project DPro)',
      '4 years of FSL programming in humanitarian settings',
    ],
    linkedin:   'https://www.linkedin.com/in/el-raham-mbursa-abb63212a',
  },

  /* ─── DEPARTMENTAL LEADERS ────────────────────────────────── */
  {
    slug:       'isaiah-yakubu',
    name:       'Isaiah Yakubu',
    role:       'Programme Coordinator',
    email:      'pc@cbi.ngo',
    photo:      '/images/team/isaiah.jpg',
    accent:     '#0102F1',
    level:      'departmental',
    location:   'Abuja, Nigeria',
    yearsAtCBI: 5,
    bio:        "Isaiah Yakubu is a development and nonprofit management professional with experience in global health, humanitarian coordination, program management, partnership development, and organizational strengthening. He has supported multi-stakeholder initiatives focused on improving the effectiveness, sustainability, and impact of nonprofit and community-based organizations. As Program Coordinator at Care Best Initiative, he leads program coordination, stakeholder engagement, partnership management, and quality assurance, working closely with technical teams and partners to drive impactful, community-centred interventions. He holds a BSc in Medical Biochemistry from the University of Benin, an MBA from Miva Open University, and is currently concluding an MPH at Federal University of Lafia.",
    shortBio:   "Development professional leading programme coordination and partnership management across all CBI thematic areas.",
    quote:      'The community always knows what it needs. Our job is to listen first.',
    expertise:  ['Program Management', 'Fundraising', 'Proposal Development', 'Grant Management', 'Public Health'],
    languages:  ['English', 'Hausa'],
    education:  ['MBA, Miva Open University', 'BSc Medical Biochemistry, University of Benin', 'MPH (in progress), Federal University of Lafia'],
    achievements: [
      'Coordinated delivery of over 20 projects across health, nutrition, WASH, FSL, education and protection',
      'FMVA certified, Corporate Finance Institute',
      'Member, Project Management Institute',
    ],
    linkedin:   'https://www.linkedin.com/in/isaiahyakubu/',
  },
  {
    slug:       'sarauniya-elbuba',
    name:       'Sarauniya El-Buba',
    role:       'Human Resource Coordinator',
    email:      'hr@cbi.ngo',
    photo:      '/images/team/sarauniya.jpg',
    accent:     '#0102F1',
    level:      'departmental',
    location:   'Maiduguri, Borno',
    yearsAtCBI: 6,
    bio:        "Sarauniya El-Buba is the Human Resources Coordinator at Care Best Initiative, overseeing people operations across eight locations in Northeast and Northwest Nigeria. With 6+ years of progressive HR experience in the humanitarian and development sector, she leads end-to-end HR functions for a workforce of 100+ staff, spanning recruitment, performance management, policy implementation, and donor compliance across CBI's multi-site operations. A certified Senior Professional in Human Resources — International (SPHRi) and Associate of the Chartered Institute of Personnel Management of Nigeria (ACIPM), Sarauniya combines operational discipline with strategic HR thinking to build people-centred organisations that are accountable, compliant, and built for impact.",
    shortBio:   "Overseeing people operations across eight CBI locations with 6+ years of HR experience in humanitarian programming.",
    quote:      'People are at the heart of every program we run.',
    expertise:  ['Workforce Planning and Recruitment', 'Organizational Development', 'Staff Relations & Conduct Management', 'Performance Management Systems'],
    languages:  ['English', 'Hausa'],
    education:  ['International Master of Business Administration'],
    achievements: [
      'SPHRi certified — Senior Professional in Human Resources International',
      'Associate, Chartered Institute of Personnel Management of Nigeria (ACIPM)',
      'Manages HR for 100+ staff across 8 locations',
    ],
    linkedin:   'https://www.linkedin.com/in/sarauniya-el-buba/',
  },
  {
    slug:       'gideon-okpuna',
    name:       'Gideon Ogbonna Okpuna',
    role:       'MEAL Coordinator',
    email:      'meal@cbi.ngo',
    photo:      '/images/team/gideon.jpg',
    accent:     '#0102F1',
    level:      'departmental',
    location:   'Maiduguri, Borno',
    yearsAtCBI: 5,
    bio:        "Ogbonna is a trained Public Health Scientist and Monitoring, Evaluation, Accountability, and Learning (MEAL) professional with over five years of experience in humanitarian and development programming. He has strong expertise in M&E systems management, humanitarian analysis, research, and knowledge management, with a focus on improving outcomes in crisis-affected communities across Nigeria. He has supported projects across WASH, Health and Nutrition, GBV/Protection, Education, and Livelihoods, using data-driven insights to strengthen service delivery in the Northeast and Northwest regions. Ogbonna is also the founder of Beacon Career Consults, an initiative through which he has trained over 150 youths in purpose discovery, career development, and leadership.",
    shortBio:   "Public Health Scientist and MEAL professional with 5+ years designing M&E systems across multi-sector humanitarian programmes.",
    quote:      'What gets measured, gets improved.',
    expertise:  ['MEAL Systems Design', 'Humanitarian Analysis', 'Research & Knowledge Management', 'Capacity Building & Coaching', 'Communication and Facilitation', 'Stakeholder Coordination'],
    languages:  ['English', 'Hausa', 'Igbo'],
    education:  ['MSc Humanitarian and Refugee Studies (MHRS)', 'BSc Public Health Science'],
    achievements: [
      'Founder of Beacon Career Consults — trained 150+ young graduates',
      'M&E systems across WASH, Health, Nutrition, GBV, Education and Livelihoods',
      '5 years of MEAL leadership in humanitarian programming',
    ],
    linkedin:   'https://www.linkedin.com/in/ogbonnaokpuna/',
  },
  {
    slug:       'jonah-renner',
    name:       'Nrior Jonah Renner',
    role:       'Finance Coordinator',
    email:      'finance@cbi.ngo',
    photo:      '/images/team/jonah.jpg',
    accent:     '#0102F1',
    level:      'departmental',
    location:   'Maiduguri, Nigeria',
    yearsAtCBI: 7,
    bio:        "Nrior Jonah Renner is a proficient finance professional and Finance Coordinator at Care Best Initiative in Maiduguri, Borno State. He leads financial operations across donor-funded projects, overseeing budgeting, reporting, compliance, and internal controls, while also serving as an internal auditor and key representative on financial matters. He holds a BSc in Accountancy from Rivers State University and is currently pursuing his ACA certification. His expertise is strengthened by professional certifications in project management, human resources, and facility management. He is proficient in QuickBooks, SAGE 50, Zoho Books, and Odoo ERP.",
    shortBio:   "Finance professional overseeing donor-funded project budgeting, reporting, and compliance across all CBI operations.",
    quote:      'Donor trust is built one financial report at a time.',
    expertise:  ['Finance, Taxation and Internal Control', 'Budgeting and Reporting', 'Audit and Compliance', 'Grant Management', 'QuickBooks, SAGE 50, Zoho Books, Odoo ERP'],
    languages:  ['English'],
    education:  ['BSc Accountancy, Rivers State University', 'ACA (in progress)'],
    achievements: [
      'Leads financial operations for all CBI donor-funded projects',
      'Proficient in QuickBooks, SAGE 50, Zoho Books and Odoo ERP',
    ],
    linkedin:   'https://www.linkedin.com/in/jonah-renner-a0b657235',
  },
  {
    slug:       'shamgar-idegwu',
    name:       'Shamgar Daniel Idegwu',
    role:       'Logistics Coordinator',
    email:      'logistics@cbi.ngo',
    photo:      '/images/team/shamgar.jpg',
    accent:     '#0102F1',
    level:      'departmental',
    location:   'Maiduguri, Nigeria',
    yearsAtCBI: 4,
    bio:        "Shamgar is a Fellow Chartered Economist and a Certified Logistics & Supply Chain Management Professional with a strong track record in operational leadership. He is a results-driven professional known for his efficiency, strategic thinking, and exceptional organisation and time management skills. In his current role, Shamgar oversees logistics and administrative operations, managing procurement, warehouse systems, fleet coordination, and facility management to ensure seamless organisational performance. He also plays a key leadership role in capacity building, conducting staff trainings and supervising Logistics Officers to ensure timely and efficient service delivery.",
    shortBio:   "Certified Logistics & Supply Chain Professional overseeing procurement, warehousing, fleet coordination, and facility management.",
    quote:      'The last mile is where humanitarian aid succeeds or fails.',
    expertise:  ['Logistics', 'Procurement', 'Fleet and Warehouse Management', 'Supply Chain Coordination', 'Capacity Building'],
    languages:  ['English', 'Hausa'],
    education:  ['BSc Economics, Adamawa State University, Mubi'],
    achievements: [
      'Fellow Chartered Economist',
      'Certified Logistics & Supply Chain Management Professional (MLSCM)',
      'Recognised for impact by both HARAF and CBI',
    ],
    linkedin:   'https://www.linkedin.com/in/shamgar-daniel-idegwu-ace-mlscm-b03054120',
  },
  {
    slug:       'samuel-holman',
    name:       'Samuel Emmanuel Holman',
    role:       'ICT Coordinator',
    email:      'ict@cbi.ngo',
    photo:      '/images/team/samuel.jpg',
    accent:     '#0102F1',
    level:      'departmental',
    location:   'Borno, Nigeria',
    yearsAtCBI: 4,
    bio:        "Samuel Emmanuel Holman is an ICT Specialist with expertise in digital communication, ICT management, and humanitarian technology solutions. As the ICT Coordinator at Care Best Initiative, he leads technology and digital communication strategies that enhance organisational operations and visibility. Skilled in digital tools, multimedia design, and system administration, he is passionate about using technology for social impact and community development. Samuel holds a BSc in Computer Science and is currently pursuing an MSc in Information Technology, alongside several professional certifications in digital communication and humanitarian information management.",
    shortBio:   "ICT Specialist leading technology and digital communication strategies that enhance CBI's operations and visibility.",
    quote:      'Good data systems make better programmes.',
    expertise:  ['ICT Management', 'Digital Media & Communication', 'Humanitarian Communication', 'System Administration', 'Multimedia Content Development', 'Microsoft Power Apps', 'Adobe Creative Suite', 'Figma Design'],
    languages:  ['English', 'Hausa'],
    education:  ['BSc Computer Science, ISCOM University', 'MSc Information Technology (in progress)'],
    achievements: [
      'Leads digital communication strategy across all CBI platforms',
      'Certified in digital communication and humanitarian information management',
    ],
    linkedin:   'https://www.linkedin.com/in/samuel-emmanuel-holman-924124221/',
  },
  {
    slug:       'deborah-oye',
    name:       'Deborah Oye',
    role:       'Admin Coordinator',
    email:      'admin@cbi.ngo',
    photo:      '/images/team/deborah.jpg',
    accent:     '#0102F1',
    level:      'departmental',
    location:   'Abuja, Nigeria',
    yearsAtCBI: 1,
    bio:        "Deborah Oye is the Administrative Coordinator at Care Best Initiative. She is a graduate of Ahmadu Bello University, where she earned a BEd in Integrated Science Education. She is currently pursuing a Diploma in Administrative Procedures and Office Support to further strengthen her expertise in administration, facility and asset management, and organisational operations. Passionate about education, coordination, and efficient service delivery, Deborah is dedicated to supporting systems that drive organisational growth and impact.",
    shortBio:   "Administrative Coordinator driving efficient service delivery and organisational operations across CBI offices.",
    quote:      'Strong organisations are built on strong administration.',
    expertise:  ['Administrative Coordination', 'Office Administration', 'Facility Management', 'Asset Management', 'Organizational Operations', 'Records and Documentation Management'],
    languages:  ['English', 'Yoruba'],
    education:  ['BEd Integrated Science Education, Ahmadu Bello University, Zaria', 'Diploma in Administrative Procedures (in progress)'],
    achievements: [
      'Coordinates administrative operations across CBI offices',
    ],
    linkedin:   'https://www.linkedin.com/in/deborah-oye-8882822ba/',
  },
  {
    slug:       'muhammad-alhaji',
    name:       'Muhammad Alhaji Muhammad',
    role:       'Information Management Officer',
    email:      'imo@cbi.ngo',
    photo:      '',
    accent:     '#7c3aed',
    level:      'departmental',
    location:   'Maiduguri, Borno',
    yearsAtCBI: 2,
    bio:        "Muhammad Alhaji Muhammad is an Information Management Officer at Care Best Initiative with experience supporting humanitarian and development programs through data management, reporting, visualisation, and information systems strengthening. His work focuses on improving data quality, reporting accountability, and decision-making across multi-sectoral interventions including Health, Nutrition, Protection, WASH, and Food Security. At CBI, he leads external sector reporting processes, develops data and information management protocols, supports dashboard development, and facilitates training on data collection, confidentiality, and reporting best practices for frontline teams.",
    shortBio:   "Information Management Officer improving data quality and reporting accountability across all CBI programme sectors.",
    quote:      'Success comes from knowing what matters to you, and showing up over and over again.',
    expertise:  ['Information Management', 'Data Analysis', 'Geospatial Analysis', 'Data Visualization', 'Capacity Building'],
    languages:  ['English', 'Hausa'],
    education:  ['BSc Software Engineering, Nigerian Army University Biu', 'MSc Information Management (in progress), Ahmadu Bello University Zaria'],
    achievements: [
      'Led development of multisectoral 5Ws reporting systems across Health, Nutrition, Protection, WASH and SRH sectors',
      'Designed data management strategies and dashboards strengthening reporting workflows',
      'Facilitated capacity-building sessions for frontline staff on data collection and reporting standards',
    ],
    linkedin:   'https://www.linkedin.com/in/muhammad-alhaji-muhammad/',
  },
  {
    slug:       'musa-amos',
    name:       'Musa Amos',
    role:       'Audit & Compliance Officer',
    email:      'm.amos@cbi.ngo',
    photo:      '',
    accent:     '#d97706',
    level:      'departmental',
    location:   'Maiduguri, Borno',
    yearsAtCBI: 1,
    bio:        "A result-oriented and goal-driven professional, Musa holds a BSc in Accounting from the University of Maiduguri. With strong expertise in audit, compliance, and finance, he serves as Internal Audit and Compliance Officer at CBI, committed to ensuring accountability, strengthening internal controls, and promoting financial integrity within the organisation.",
    shortBio:   "Audit and Compliance Officer ensuring accountability, internal controls, and financial integrity across CBI operations.",
    quote:      'Accountability is not just compliance — it is a commitment to the communities we serve.',
    expertise:  ['Audit and Compliance', 'Finance', 'Internal Controls', 'Financial Integrity'],
    languages:  ['English', 'Hausa'],
    education:  ['BSc Accounting, University of Maiduguri'],
    achievements: [
      'Strengthening internal audit and compliance systems at CBI',
    ],
    linkedin:   'https://www.linkedin.com/in/amos-musa60a373149',
  },
  {
    slug:       'mai-ibrahim',
    name:       'Mai Ibrahim',
    role:       'Legal Adviser',
    email:      'maiibrahim481@gmail.com',
    photo:      '/images/team/mai.jpg',
    accent:     '#0102F1',
    level:      'departmental',
    location:   'Maiduguri, Borno',
    yearsAtCBI: 1,
    bio:        "Mai Ibrahim is a legal practitioner based in Maiduguri, Borno State, with a solid academic and professional background in law. He obtained his Bachelor of Laws (LLB) degree from the University of Maiduguri in 2017 and attended the Nigerian Law School, Victoria Island Campus, Lagos, in 2018. He was called to the Nigerian Bar by the Body of Benchers of the Federal Republic of Nigeria in 2019 and is currently practising as a private legal practitioner. He is an active member of the Nigerian Bar Association, Maiduguri Branch.",
    shortBio:   "Legal practitioner called to the Nigerian Bar, providing legal drafting, advisory, and consultation services to CBI.",
    quote:      'Sound legal foundations protect the organisations that protect communities.',
    expertise:  ['Legal Advisory', 'Legal Drafting and Consultation', 'Regulatory Compliance'],
    languages:  ['English', 'Hausa', 'Kanuri'],
    education:  ['LLB, University of Maiduguri', 'Nigerian Law School, Victoria Island, Lagos'],
    achievements: [
      'Called to the Nigerian Bar by the Body of Benchers, 2019',
      'Active member, Nigerian Bar Association, Maiduguri Branch',
    ],
    linkedin:   '#',
  },
]

export const EXECUTIVE     = TEAM.filter(m => m.level === 'executive')
export const THEMATIC      = TEAM.filter(m => m.level === 'thematic')
export const DEPARTMENTAL  = TEAM.filter(m => m.level === 'departmental')

// Backward-compat aliases used by [slug] profile page
export const LEADERSHIP    = EXECUTIVE
export const STAFF         = [...THEMATIC, ...DEPARTMENTAL]

export function getMember(slug: string): TeamMember | undefined {
  return TEAM.find(m => m.slug === slug)
}

/** Returns true when the member has a real headshot in /images/team/ */
export function hasHeadshot(photo: string): boolean {
  return Boolean(photo) && photo.startsWith('/images/team/')
}
